"""Added all trip columns

Revision ID: 6dc61319de57
Revises: c7b7a6f61ea0
Create Date: 2026-02-19 14:26:03.072262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc61319de57'
down_revision = 'c7b7a6f61ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_offloaded', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('loading_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('offloading_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('time_taken', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('eta', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('offloading_point', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('trailer_reg', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('customer', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('product', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dn_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('allowance_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('litres_loaded', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('litres_offloaded', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('difference', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('loading_km', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('offloading_km', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('km_travelled', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('km_travelled')
        batch_op.drop_column('offloading_km')
        batch_op.drop_column('loading_km')
        batch_op.drop_column('difference')
        batch_op.drop_column('litres_offloaded')
        batch_op.drop_column('litres_loaded')
        batch_op.drop_column('allowance_status')
        batch_op.drop_column('dn_number')
        batch_op.drop_column('position')
        batch_op.drop_column('status')
        batch_op.drop_column('product')
        batch_op.drop_column('customer')
        batch_op.drop_column('trailer_reg')
        batch_op.drop_column('offloading_point')
        batch_op.drop_column('eta')
        batch_op.drop_column('time_taken')
        batch_op.drop_column('offloading_time')
        batch_op.drop_column('loading_time')
        batch_op.drop_column('date_offloaded')

    # ### end Alembic commands ###
