"""Fresh start with proper naming

Revision ID: c7b7a6f61ea0
Revises: 
Create Date: 2026-02-19 14:20:06.421994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b7a6f61ea0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_driver')),
    sa.UniqueConstraint('name', name=op.f('uq_driver_name'))
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_reg', sa.String(length=20), nullable=False),
    sa.Column('truck_type', sa.String(length=50), nullable=True),
    sa.Column('truck_vin', sa.String(length=50), nullable=True),
    sa.Column('trailer_reg', sa.String(length=20), nullable=True),
    sa.Column('trailer_type', sa.String(length=50), nullable=True),
    sa.Column('trailer_vin', sa.String(length=50), nullable=True),
    sa.Column('pto_avail', sa.String(length=10), nullable=True),
    sa.Column('driver', sa.String(length=100), nullable=True),
    sa.Column('current_km', sa.Float(), nullable=True),
    sa.Column('last_km_update', sa.DateTime(), nullable=True),
    sa.Column('last_service_km', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle')),
    sa.UniqueConstraint('truck_reg', name=op.f('uq_vehicle_truck_reg'))
    )
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('date_loaded', sa.DateTime(), nullable=True),
    sa.Column('loading_point', sa.String(length=100), nullable=True),
    sa.Column('truck_reg', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], name=op.f('fk_trip_driver_id_driver')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name=op.f('fk_trip_vehicle_id_vehicle')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip')),
    sa.UniqueConstraint('order_number', name=op.f('uq_trip_order_number'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    op.drop_table('vehicle')
    op.drop_table('driver')
    # ### end Alembic commands ###
